## Baixa e executa a imagem do node na versão Alpine (versão simplificada)
FROM node:alpine

##docker-compose up --build

##docker-compose down -v

## Define o local onde o app irá rodar no disco do container
## O caminho do Dev quem escolhe
WORKDIR /usr/app

## Copia tudo que começa com package e termina com .json para dentro do usr/app
COPY package*.json ./

## Executa npm install para adicionar todas as dependencias e criar a pasta node_modules
RUN npm install

## Copia tudo que esta no diretorio onde o arquinvo Dockerfile esta
## Será copiado dentro da pasra /usr/app do container
## Vamos ignorar o node_modules (.dockerignore)
COPY . .

## Container ficará ouvindo os acessos na porta 5000
EXPOSE 5000

## Executa o comando para iniciar o script que está no package.json
CMD npm start